// flow-typed signature: 5873423cb36bd4e3e95c390fe55c6695
// flow-typed version: <<STUB>>/@forge/bridge_v^3.4.0/flow_v0.239.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@forge/bridge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@forge/bridge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@forge/bridge/out/bridge' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/errors' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/events/events' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/events' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/fetch/fetch' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/fetch' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/flag/flag' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/flag' {
  declare module.exports: any;
}

declare module '@forge/bridge/out' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/invoke-remote' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/invoke-remote/invoke-remote' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/invoke' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/invoke/invoke' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/modal' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/modal/modal' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/router' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/router/router' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/types' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/utils/blobParser' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/utils' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/view/close' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/view/createHistory' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/view/getContext' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/view' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/view/refresh' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/view/submit' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/view/theme' {
  declare module.exports: any;
}

declare module '@forge/bridge/out/view/view' {
  declare module.exports: any;
}

// Filename aliases
declare module '@forge/bridge/out/bridge.js' {
  declare module.exports: $Exports<'@forge/bridge/out/bridge'>;
}
declare module '@forge/bridge/out/errors.js' {
  declare module.exports: $Exports<'@forge/bridge/out/errors'>;
}
declare module '@forge/bridge/out/events/events.js' {
  declare module.exports: $Exports<'@forge/bridge/out/events/events'>;
}
declare module '@forge/bridge/out/events/index' {
  declare module.exports: $Exports<'@forge/bridge/out/events'>;
}
declare module '@forge/bridge/out/events/index.js' {
  declare module.exports: $Exports<'@forge/bridge/out/events'>;
}
declare module '@forge/bridge/out/fetch/fetch.js' {
  declare module.exports: $Exports<'@forge/bridge/out/fetch/fetch'>;
}
declare module '@forge/bridge/out/fetch/index' {
  declare module.exports: $Exports<'@forge/bridge/out/fetch'>;
}
declare module '@forge/bridge/out/fetch/index.js' {
  declare module.exports: $Exports<'@forge/bridge/out/fetch'>;
}
declare module '@forge/bridge/out/flag/flag.js' {
  declare module.exports: $Exports<'@forge/bridge/out/flag/flag'>;
}
declare module '@forge/bridge/out/flag/index' {
  declare module.exports: $Exports<'@forge/bridge/out/flag'>;
}
declare module '@forge/bridge/out/flag/index.js' {
  declare module.exports: $Exports<'@forge/bridge/out/flag'>;
}
declare module '@forge/bridge/out/index' {
  declare module.exports: $Exports<'@forge/bridge/out'>;
}
declare module '@forge/bridge/out/index.js' {
  declare module.exports: $Exports<'@forge/bridge/out'>;
}
declare module '@forge/bridge/out/invoke-remote/index' {
  declare module.exports: $Exports<'@forge/bridge/out/invoke-remote'>;
}
declare module '@forge/bridge/out/invoke-remote/index.js' {
  declare module.exports: $Exports<'@forge/bridge/out/invoke-remote'>;
}
declare module '@forge/bridge/out/invoke-remote/invoke-remote.js' {
  declare module.exports: $Exports<'@forge/bridge/out/invoke-remote/invoke-remote'>;
}
declare module '@forge/bridge/out/invoke/index' {
  declare module.exports: $Exports<'@forge/bridge/out/invoke'>;
}
declare module '@forge/bridge/out/invoke/index.js' {
  declare module.exports: $Exports<'@forge/bridge/out/invoke'>;
}
declare module '@forge/bridge/out/invoke/invoke.js' {
  declare module.exports: $Exports<'@forge/bridge/out/invoke/invoke'>;
}
declare module '@forge/bridge/out/modal/index' {
  declare module.exports: $Exports<'@forge/bridge/out/modal'>;
}
declare module '@forge/bridge/out/modal/index.js' {
  declare module.exports: $Exports<'@forge/bridge/out/modal'>;
}
declare module '@forge/bridge/out/modal/modal.js' {
  declare module.exports: $Exports<'@forge/bridge/out/modal/modal'>;
}
declare module '@forge/bridge/out/router/index' {
  declare module.exports: $Exports<'@forge/bridge/out/router'>;
}
declare module '@forge/bridge/out/router/index.js' {
  declare module.exports: $Exports<'@forge/bridge/out/router'>;
}
declare module '@forge/bridge/out/router/router.js' {
  declare module.exports: $Exports<'@forge/bridge/out/router/router'>;
}
declare module '@forge/bridge/out/types.js' {
  declare module.exports: $Exports<'@forge/bridge/out/types'>;
}
declare module '@forge/bridge/out/utils/blobParser.js' {
  declare module.exports: $Exports<'@forge/bridge/out/utils/blobParser'>;
}
declare module '@forge/bridge/out/utils/index' {
  declare module.exports: $Exports<'@forge/bridge/out/utils'>;
}
declare module '@forge/bridge/out/utils/index.js' {
  declare module.exports: $Exports<'@forge/bridge/out/utils'>;
}
declare module '@forge/bridge/out/view/close.js' {
  declare module.exports: $Exports<'@forge/bridge/out/view/close'>;
}
declare module '@forge/bridge/out/view/createHistory.js' {
  declare module.exports: $Exports<'@forge/bridge/out/view/createHistory'>;
}
declare module '@forge/bridge/out/view/getContext.js' {
  declare module.exports: $Exports<'@forge/bridge/out/view/getContext'>;
}
declare module '@forge/bridge/out/view/index' {
  declare module.exports: $Exports<'@forge/bridge/out/view'>;
}
declare module '@forge/bridge/out/view/index.js' {
  declare module.exports: $Exports<'@forge/bridge/out/view'>;
}
declare module '@forge/bridge/out/view/refresh.js' {
  declare module.exports: $Exports<'@forge/bridge/out/view/refresh'>;
}
declare module '@forge/bridge/out/view/submit.js' {
  declare module.exports: $Exports<'@forge/bridge/out/view/submit'>;
}
declare module '@forge/bridge/out/view/theme.js' {
  declare module.exports: $Exports<'@forge/bridge/out/view/theme'>;
}
declare module '@forge/bridge/out/view/view.js' {
  declare module.exports: $Exports<'@forge/bridge/out/view/view'>;
}
